[package]
name = "remote-m8-ui"
version = "0.1.0"
authors = ["Jeffery Utter <jeff@jeffutter.com>"]
edition = "2021"

[dependencies]
simple_slip = "0.1.2"
macroquad = "0.4.13"
quad-net = "0.1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
